[package]
name = "udf-examples"
version = "0.4.5"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
udf = { path = "../udf", features = ["mock"] }
lipsum = "0.8.2"
uuid = { version = "1.1.2", features = ["v1", "v3", "v4", "v5", "fast-rng"] }

[dev-dependencies]
diesel = { version = "2.0.2", features = ["mysql"] }
lazy_static = "1.4.0"

[features]
# Used to optionally enable integration tests
backend = []
