[package]
name = "udf-uuid"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
udf = "0.3.5"
uuid = { version = "1.2.1", features = ["v1", "v3", "v4", "v5", "fast-rng"] }
