[package]
name = "udf-lipsum"
version = "0.1.4"
edition = "2021"
publish = false
license = "Apache-2.0 OR GPL-2.0-or-later"

[lib]
crate-type = ["cdylib"]

[dependencies]
udf = { version = "0.5", features = ["mock"] }
lipsum = "0.8.2"
